export enum CategoryEnum {
  STATUS = 500,
    ACTIVE = 501,
    INACTIVE = 502,
    DELETED = 503,
  OPERATION_COST_CATEGORY = 510,
    OCC_MAINTENANCE_FOR_VEHICLES = 511,
    OCC_INSURANCE_FOR_VEHICLES = 512,
    OCC_PACKAGING_MATERIALS = 513,
    OCC_STORAGE_SPACE = 514,
    OCC_CORPORATE_TAXES = 515,
    OCC_VARIABLE_COSTS = 516,
}
